### ISSUE TITLE
Improvements of visual entities and types

### ISSUE THREAD

**Issue by Nipheris** [LandRushGIS/IO#1]
Implement type for color values. Use this type in other visual entities (fonts, pens, brushes). Sample type: [System.Drawing.Color](http://msdn.microsoft.com/en-us/library/system.drawing.color.aspx)

Color is represented by 4-byte integer value using the following structure:
++++++++++++++++++++++++++++
| unused |----B----|----G----|----R----|
------3---------2---------1---------0-----

Implement enums for font, pen and brush styles using Borland VCL constants. Following links might be useful. Pen:
http://msdn.microsoft.com/en-us/library/dd145041.aspx
http://docwiki.embarcadero.com/Libraries/XE7/en/Vcl.Graphics.TPenStyle (psUserStyle, psAlternate is not used).

Brush:
http://docwiki.embarcadero.com/Libraries/XE7/en/Vcl.Graphics.TBrushStyle

Font:
http://docwiki.embarcadero.com/Libraries/XE7/en/Vcl.Graphics.TFontStyle

Bitmask for style byte:
0 bit - Bold
1 bit - Italic
2 bit - Underline
3 bit - StrikeOut
4-7 bits - unused

Also, font name conforms the following structure:

`Name:CharSet`

For example,

`Arial:204`

We should extract the charset located after the font face name, and convert it to "byte" type. If no ":" character presents in the name string, we should use Default charset

Summary view of Font object properties:
- Bold: bool;
- Italic: bool;
- Underline: bool;
- StrikeOut: bool;
- Color: Color;
- Name: string;
- CharSet: byte;
- Size: float;

**Comment by vaerizk** [comment]
resolved by e67a816f97a169d44670a0e692c603be66437d58
