### ISSUE TITLE
Improve symbols support: polylines, primitive hierarchy.

### ISSUE THREAD

**Issue by Nipheris** [LandRushGIS/IO#3]
As it was discovered, symbol primitives has more complex structure, than defined in official spec. Our investigations show that single polyline in symbol can be defined using several sequential primitives, and line break markers, similar to markers in feature coordinate sequences, is used to split polyline. From this perspective, using primitive classes with only two points and type descriminator seems unsuitable. Proposition is to build simple hierarchy with primitive classes (with immutable state), each containing properties related to specific primitive (line with start and end points, circle with center and radius, polyline with array of points and so on).

**Comment by vaerizk** [comment]
resolved by b851a293e99051e32f38b6661b7ba0e6f25e7c5f
